// lib/vectorStore.js
// Temporary mock vector store until Step 31 (real DB integration)

export const vectorStore = {
  async search(queryEmbedding, topK) {
    // Mock memory result for testing the memory engine pipeline

    return [
      {
        memoryId: "mock-memory-1",
        text: "This is a mock memory result generated by the temporary vector store.",
        score: 0.85,
        metadata: {
          priority: 5,
          timestamp: Date.now()
        }
      },
      {
        memoryId: "mock-memory-2",
        text: "Another mock memory result for verifying top-K behavior.",
        score: 0.65,
        metadata: {
          priority: 3,
          timestamp: Date.now()
        }
      }
    ].slice(0, topK);
  }
};

